#!/bin/sh
exec tail -n +3 $0
# By default the flag file is stored in /boot, so try to find the
# boot partition. On UEFI this may different than the grub
# $root so we search for it here.
# https://github.com/coreos/ignition-dracut/issues/51
# The path may also be set by previous grub scripts.
if [ -z "${ignition_flagdir}" ]; then
    search --set=ignition_flagdir --label boot
    set ignition_flagdir="(${ignition_flagdir})"
fi
# Determine if this is a first boot and set the variable
# to be used later on the kernel command line.
set ignition_firstboot=""
if [ -f "${ignition_flagdir}/ignition.firstboot" ]; then
    # default to dhcp networking parameters to be used with ignition 
    set ignition_network_kcmdline='rd.neednet=1 ip=dhcp'

    # source in the `ignition.firstboot` file which could override the
    # above $ignition_network_kcmdline with static networking config.
    # This override feature is primarily used by coreos-installer to
    # persist static networking config provided during install to the    
    # first boot of the machine.
    source "${ignition_flagdir}/ignition.firstboot"
    
    # we support setting variables in the 
    set ignition_firstboot="ignition.firstboot $ignition_network_kcmdline"
fi
